apiVersion: shop.pilab.hu/v1alpha1
kind: PRStack
metadata:
  name: prstack-sample-enhanced
  namespace: default
spec:
  # PR number for this stack
  prNumber: "123"
  
  # Custom image tag for services (optional - defaults to pr-{prNumber})
  # Examples: "v1.2.3", "latest", "pr-123-abc123"
  imageTag: "v1.2.3"
  
  # Custom domain for ingress (optional - defaults to pr-{prNumber}.{BASE_DOMAIN})
  # Examples: "gyurushop.hu", "magicshop.hu", "tenant1.example.com"
  customDomain: "gyurushop.hu"
  
  # TLS secret name for HTTPS (optional - no TLS if not specified)
  # The secret should contain 'tls.crt' and 'tls.key' keys
  # Examples: "gyurushop-tls", "magicshop-tls"
  ingressTlsSecretName: "gyurushop-tls"
  
  # Active controls whether the stack is running (true) or de-provisioned (false)
  # When false: all deployments scaled to 0 replicas
  # When true: all deployments scaled to 1 replica with fresh images
  active: true
  
  # Services to deploy for this PR (optional - defaults to all services)
  services:
    - "product-service"
    - "cart-service"
    - "order-service"
    - "payment-service"
    - "customer-service"
    - "inventory-service"
    - "notification-service"
    - "discount-service"
    - "checkout-service"
    - "analytics-service"
    - "auth-service"
    - "graphql-service"
  
  # Environment configuration
  environment: "pr"
  
  # Resource limits for the PR environment
  resourceLimits:
    cpuLimit: "500m"
    memoryLimit: "1Gi"
    storageLimit: "10Gi"
  
  # Connection details (optional - uses operator defaults if not specified)
  mongoURI: "mongodb://mongodb.pishop-base.svc.cluster.local:27017"
  mongoUsername: "admin"
  mongoPassword: "password"
  natsURL: "nats://nats.pishop-base.svc.cluster.local:4222"
  redisURL: "redis://redis.pishop-base.svc.cluster.local:6379"
