apiVersion: shop.pilab.hu/v1alpha1
kind: PRStack
metadata:
  name: prstack-production-tenant
  namespace: default
spec:
  # PR number for this stack (can be a tenant identifier for production)
  prNumber: "tenant1"
  
  # Custom image tag for production services
  # Use semantic versioning or stable tags for production
  imageTag: "v1.5.2"
  
  # Custom domain for production tenant
  # This will be used for ingress instead of the default pattern
  customDomain: "magicshop.hu"
  
  # TLS secret name for HTTPS (required for production)
  # The secret should contain 'tls.crt' and 'tls.key' keys
  ingressTlsSecretName: "magicshop-tls"
  
  # Active controls whether the stack is running (true) or de-provisioned (false)
  # When false: all deployments scaled to 0 replicas
  # When true: all deployments scaled to 1 replica with fresh images
  active: true
  
  # Services to deploy for this tenant (optional - defaults to all services)
  services:
    - "product-service"
    - "cart-service"
    - "order-service"
    - "payment-service"
    - "customer-service"
    - "inventory-service"
    - "notification-service"
    - "discount-service"
    - "checkout-service"
    - "analytics-service"
    - "auth-service"
    - "graphql-service"
  
  # Environment configuration
  environment: "production"
  
  # Resource limits for the production environment (higher than PR environments)
  resourceLimits:
    cpuLimit: "1000m"
    memoryLimit: "2Gi"
    storageLimit: "50Gi"
  
  # Connection details (optional - uses operator defaults if not specified)
  mongoURI: "mongodb://mongodb.pishop-base.svc.cluster.local:27017"
  mongoUsername: "admin"
  mongoPassword: "password"
  natsURL: "nats://nats.pishop-base.svc.cluster.local:4222"
  redisURL: "redis://redis.pishop-base.svc.cluster.local:6379"
  
  # Backup configuration for production
  backupConfig:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retentionDays: 30
    storageClass: "fast-ssd"
    storageSize: "100Gi"
